 steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-service:$COMMIT_SHA', '--build-arg=DB_URL=$_DB_URL','JWT_SECRET=$_JWT_SECRET', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-service:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'backend-service'
    - '--image'
    - 'gcr.io/$PROJECT_ID/backend-service:$COMMIT_SHA'
    - '--region'
    - 'asia-southeast2'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
substitutions:
    _DB_URL: 'mysql://username:password@localhost:3306/dbname' # default value
    _JWT_SECRET: 'adadahuafuauafgauf'
